networks:
  tails-and-claws-network:
    driver: bridge

volumes:
  tails-and-claws-logs: {}
  tails-and-claws-pgdata: {}

services:
  tails-and-claws:
    container_name: tails-and-claws-backend
    image: ${DOCKER_REGISTRY-}tails-and-claws:latest
    depends_on:
      - db-storage
    restart: always

    build:
      context: .
      dockerfile: src/TailsAndClaws/Dockerfile
      args:
        TC_CERT_PASSWORD: ${TC_CERT_PASSWORD}

    ports:
      - ${APP_HTTP_PORT}:${HOST_HTTP_PORT}
      - ${APP_HTTPS_PORT}:${HOST_HTTPS_PORT}

    environment:
      ASPNETCORE_ENVIRONMENT: ${APPLICATION_ENVIRONMENT_NAME}
      ConnectionStrings__Application: ${APPLICATION_CONNECTION_STRING}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${TC_CERT_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/tailsAndClaws.pfx
      SEEDING: ${INCLUDE_SEEDING}
      ASPNETCORE_URLS: http://+:${HOST_HTTP_PORT};https://+:${HOST_HTTPS_PORT}

    networks:
      - tails-and-claws-network

    volumes:
      - tails-and-claws-logs:/app/tails-and-claws-logs

  db-storage:
    container_name: tails-and-claws-postgresql
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PORT: ${PG_PORT}

    ports:
      - ${PG_PORT}:${PG_HOST_PORT}

    networks:
      - tails-and-claws-network

    volumes:
      - tails-and-claws-pgdata:/var/lib/postgresql/data
