name: CI For TailsAndClaws

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build-and-test-remote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore TailsAndClaws.sln
      
    - name: Build Solution
      run: dotnet build TailsAndClaws.sln --configuration Release --no-restore
      
    - name: Run Unit Tests
      run: dotnet test tests/TailsAndClaws.UnitTests/TailsAndClaws.UnitTests.csproj --no-restore --verbosity normal
      
    - name: Run Shared Unit Tests
      run: dotnet test tests/AMSaiian.Shared.UnitTests/AMSaiian.Shared.UnitTests.csproj --no-restore --verbosity normal
